### ISSUE TITLE
Unreachable macro call for token initialization

### ISSUE THREAD

**Issue by sal1ent** [TypeSharp/Typesharp#18]
Referenced here:

https://github.com/TypeSharp/Typesharp/blob/fd977035456f9f8b3e6f259fb5f1cdfb50086151/src/compiler/typesharp_lexer/token.rs#L200

**Comment by sal1ent** [comment]
This is due to the match arm here: 

https://github.com/TypeSharp/Typesharp/blob/fd977035456f9f8b3e6f259fb5f1cdfb50086151/src/compiler/typesharp_lexer/token.rs#L195

**Comment by Bavfalcon9** [comment]
Yeah, this is intended, at least it was. As I wasn't sure how I wanted to go about lexing strings.
